spring:
  application:
    name: gateway-sentinel-sample
  cloud:
    gateway:
      routes:
        - id: test
          uri: lb://RULE-LITEFLOW
          predicates:
            - Path=/api-a/**

#        - id: deny-get-method
#          uri: forward:/deny-get-method
#          predicates:
#            - Method=GET
      discovery:
        locator:
          enabled: true
    sentinel:
      # sentinel是懒加载机制，只有访问过一次的资源才会被监控
      # 取消控制台懒加载，项目启动即连接Sentinel
      eager: true
      transport:
        dashboard: localhost:8888
        port: 8719
        client-ip: 192.168.65.175
      scg:
        fallback:
          mode: response
          content-type: application/json;charset=UTF-8
          response-status: 429
          response-body: "{\"return_code\":\"FAIL\",\"return_msg\":\"请求过多！\"}"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/


server:
  port: 8082

sm:
  sm4key: Uh3lIbRvcUfmwTw1/nUFDw==
