spring:
  application:
    name: gateway-sentinel-sample
  cloud:
    gateway:
      routes:
        - id: deny-get-method
          uri: forward:/deny-get-method
          predicates:
            - Method=GET
      discovery:
        locator:
          enabled: true
    sentinel:
      # sentinel是懒加载机制，只有访问过一次的资源才会被监控
      # 取消控制台懒加载，项目启动即连接Sentinel
      eager: true
      scg:
        fallback:
          mode: response
          content-type: application/json;charset=UTF-8
          response-status: 429
          response-body: "{\"return_code\":\"FAIL\",\"return_msg\":\"请求过多！\"}"
  config:
    activate:
      on-profile: dev
  jackson:
    date-format: yyyyMMddHHMMss
    time-zone: GMT+8


server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8


logging:
  level:
    root: info


