spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8888
        port: 8719
        client-ip: 192.168.65.175


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/


sm:
  sm4key: Uh3lIbRvcUfmwTw1/nUFDw==